name: Scheduled Tests

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日00:00 UTCに実行
  workflow_dispatch:  # 手動トリガーも可能

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Send notification on failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: 'danger'
        SLACK_TITLE: 'Scheduled Test Failed'
        SLACK_MESSAGE: 'The scheduled test run for JS_gym has failed.'
